// Synthetic data: effectively unlimited intraday history (multi-year backtests).
export const INTRADAY_MAX_DAYS = 3650;

// Synthetic market-data provider with the SAME interface as yahoo.js.
// Used when DATA_SOURCE=mock (offline demos, CI, or networks that block Yahoo).
// Prices are generated by a per-symbol seeded random walk so charts are stable
// across requests. This is NOT real market data — it is clearly labelled as
// simulated in the UI's exchange field.

const CATALOG = [
  { symbol: 'AAPL', name: 'Apple Inc.', exchange: 'NASDAQ', base: 195, cap: 3.0e12, sector: 'Technology', industry: 'Consumer Electronics' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', exchange: 'NASDAQ', base: 430, cap: 3.2e12, sector: 'Technology', industry: 'Software—Infrastructure' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', exchange: 'NASDAQ', base: 120, cap: 2.9e12, sector: 'Technology', industry: 'Semiconductors' },
  { symbol: 'TSLA', name: 'Tesla, Inc.', exchange: 'NASDAQ', base: 250, cap: 8.0e11, sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.', exchange: 'NASDAQ', base: 185, cap: 1.9e12, sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', exchange: 'NASDAQ', base: 175, cap: 2.1e12, sector: 'Communication Services', industry: 'Internet Content' },
  { symbol: 'META', name: 'Meta Platforms, Inc.', exchange: 'NASDAQ', base: 500, cap: 1.3e12, sector: 'Communication Services', industry: 'Internet Content' },
  { symbol: 'AMD', name: 'Advanced Micro Devices, Inc.', exchange: 'NASDAQ', base: 160, cap: 2.6e11, sector: 'Technology', industry: 'Semiconductors' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', exchange: 'NYSE', base: 200, cap: 5.7e11, sector: 'Financial Services', industry: 'Banks—Diversified' },
  { symbol: 'KO', name: 'The Coca-Cola Company', exchange: 'NYSE', base: 62, cap: 2.7e11, sector: 'Consumer Defensive', industry: 'Beverages' },
  { symbol: 'DIS', name: 'The Walt Disney Company', exchange: 'NYSE', base: 100, cap: 1.8e11, sector: 'Communication Services', industry: 'Entertainment' },
  { symbol: 'NKE', name: 'NIKE, Inc.', exchange: 'NYSE', base: 75, cap: 1.1e11, sector: 'Consumer Cyclical', industry: 'Footwear & Accessories' },
];

import { normalizeSpread } from './yahoo.js';

const bySymbol = new Map(CATALOG.map((c) => [c.symbol, c]));

// A stable per-symbol half-spread in basis points (2–12 bps) so each stock has
// its own realistic spread. Cheaper/large-cap names get tighter spreads.
function spreadFor(symbol, price) {
  const c = bySymbol.get(symbol);
  const rand = mulberry32(seedFor(symbol) ^ 0x5f3759df);
  const capT = (c?.cap || 5e10) / 1e12;
  const bps = 2 + rand() * 10 - Math.min(4, capT); // wider for small caps
  const half = Math.max(0.01, (price * Math.max(1, bps)) / 20000);
  return normalizeSpread(price, price - half, price + half);
}

function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
function seedFor(symbol) {
  let h = 2166136261;
  for (const ch of symbol) h = Math.imul(h ^ ch.charCodeAt(0), 16777619);
  return h >>> 0;
}

const INTERVAL_SEC = {
  '1m': 60,
  '5m': 300,
  '15m': 900,
  '30m': 1800,
  '60m': 3600,
  '1h': 3600,
  '1d': 86400,
  '1wk': 7 * 86400,
  '1mo': 30 * 86400,
};
const RANGE_SEC = {
  '1d': 86400,
  '5d': 5 * 86400,
  '1mo': 30 * 86400,
  '3mo': 91 * 86400,
  '6mo': 182 * 86400,
  '1y': 365 * 86400,
  '2y': 730 * 86400,
  '5y': 1825 * 86400,
  max: 12 * 365 * 86400,
};

function meta(symbol) {
  const c = bySymbol.get(symbol);
  return c || { symbol, name: `${symbol} (simulated)`, exchange: 'NASDAQ', base: 100, cap: 5e10, sector: 'Technology', industry: 'Software' };
}

// Build a stable random-walk series at the given native interval over the range.
function series(symbol, range, interval, nowSec) {
  const c = meta(symbol);
  const step = INTERVAL_SEC[interval] || 1800;
  const span = RANGE_SEC[range] || RANGE_SEC['1mo'];
  // Synthetic data has no history limit, so allow a much larger cap for intraday
  // bars — this is what makes multi-year intraday backtests possible in demo mode.
  const cap = step < 86400 ? 40000 : 1500;
  const count = Math.max(2, Math.min(cap, Math.round(span / step)));
  const rand = mulberry32(seedFor(symbol) ^ seedFor(range) ^ seedFor(interval));
  const bars = [];
  let price = c.base * (0.75 + rand() * 0.1);
  // Anchor bar times to a fixed grid (aligned to the interval) so timestamps are
  // stable across calls within the same interval — like real market bars. This
  // keeps signal identity stable (a new bar only appears when the grid advances).
  const lastAligned = Math.floor(nowSec / step) * step;
  const start = lastAligned - (count - 1) * step;
  // Volatility grows with bar length so a monthly candle swings more than a
  // 1-minute one, capped so long bars stay sane.
  const vol = Math.min(c.base * 0.12, c.base * 0.006 * Math.sqrt(step / 3600));
  for (let i = 0; i < count; i++) {
    const drift = (c.base - price) * 0.002; // gentle mean reversion toward base
    const shock = (rand() - 0.5) * 2 * vol;
    const open = price;
    const close = Math.max(1, open + drift + shock);
    const high = Math.max(open, close) + rand() * vol * 0.8;
    const low = Math.min(open, close) - rand() * vol * 0.8;
    const volume = Math.round((5e5 + rand() * 4e6) * (c.cap / 1e12 + 0.3) * (step / 1800));
    bars.push({ time: start + i * step, open, high, low, close, volume });
    price = close;
  }
  return bars;
}

export async function search(query) {
  const q = (query || '').trim().toLowerCase();
  if (!q) return [];
  return CATALOG.filter(
    (c) => c.symbol.toLowerCase().includes(q) || c.name.toLowerCase().includes(q)
  ).map((c) => ({ symbol: c.symbol, name: c.name, exchange: c.exchange, type: 'EQUITY' }));
}

export async function chart(symbol, range = '1mo', interval = '1d') {
  symbol = symbol.toUpperCase();
  const nowSec = Math.floor(Date.now() / 1000);
  const bars = series(symbol, range, interval, nowSec);
  const c = meta(symbol);
  const last = bars[bars.length - 1];
  return {
    meta: {
      symbol,
      currency: 'USD',
      exchange: `${c.exchange} (simulated)`,
      regularMarketPrice: last.close,
      previousClose: bars.length > 1 ? bars[bars.length - 2].close : last.open,
      regularMarketTime: nowSec,
    },
    bars,
  };
}

export async function quote(symbol) {
  symbol = symbol.toUpperCase();
  const c = meta(symbol);
  const ch = await chart(symbol, '1y', '1d');
  const bars = ch.bars;
  const closes = bars.map((b) => b.close);
  // Use the intraday series for the *live* price so the quote matches the price
  // orders actually fill at (lastPrice() reads the same series).
  const intraday = (await chart(symbol, '5d', '5m')).bars;
  const last = intraday[intraday.length - 1];
  const prev = intraday[intraday.length - 2] || { close: last.open };
  const rand = mulberry32(seedFor(symbol));
  const eps = +(last.close / (12 + rand() * 25)).toFixed(2);
  const sp = spreadFor(symbol, last.close);
  return {
    symbol,
    name: c.name,
    exchange: `${c.exchange} (simulated)`,
    currency: 'USD',
    price: last.close,
    bid: sp.bid,
    ask: sp.ask,
    bidSize: Math.round(1 + rand() * 40) * 100,
    askSize: Math.round(1 + rand() * 40) * 100,
    spread: +(sp.ask - sp.bid).toFixed(4),
    spreadEstimated: false,
    previousClose: prev.close,
    change: last.close - prev.close,
    changePercent: ((last.close - prev.close) / prev.close) * 100,
    dayHigh: last.high,
    dayLow: last.low,
    open: last.open,
    volume: last.volume,
    avgVolume: Math.round(bars.reduce((a, b) => a + b.volume, 0) / bars.length),
    marketCap: c.cap,
    peRatio: +(last.close / eps).toFixed(2),
    forwardPE: +(last.close / (eps * 1.12)).toFixed(2),
    eps,
    beta: +(0.8 + rand() * 1.2).toFixed(2),
    dividendYield: rand() > 0.5 ? +(rand() * 0.03).toFixed(4) : null,
    fiftyTwoWeekHigh: Math.max(...closes, last.close),
    fiftyTwoWeekLow: Math.min(...closes, last.close),
    fiftyDayAverage: avg(closes.slice(-50)),
    twoHundredDayAverage: avg(closes.slice(-200)),
    sharesOutstanding: Math.round(c.cap / last.close),
    sector: c.sector,
    industry: c.industry,
    website: `https://example.com/${symbol.toLowerCase()}`,
    employees: Math.round(5000 + rand() * 200000),
    description: `${c.name} is a simulated ${c.sector} company used for offline demos of the Shubh Quant Dashboard platform. Prices shown here are generated by a seeded random walk and do not represent real market data. Set DATA_SOURCE=yahoo (the default) to trade against live NYSE/NASDAQ prices.`,
    targetMeanPrice: +(last.close * (0.9 + rand() * 0.3)).toFixed(2),
    recommendation: ['buy', 'hold', 'strong_buy', 'underperform'][Math.floor(rand() * 4)],
  };
}

export async function lastPrice(symbol) {
  const ch = await chart(symbol, '5d', '5m');
  const last = ch.bars[ch.bars.length - 1];
  const sp = spreadFor(symbol.toUpperCase(), last.close);
  return {
    symbol: symbol.toUpperCase(),
    price: last.close,
    previousClose: ch.meta.previousClose,
    bid: sp.bid,
    ask: sp.ask,
    spreadEstimated: false,
  };
}

function avg(a) {
  return a.length ? a.reduce((x, y) => x + y, 0) / a.length : null;
}
